# Local Configuration Variables

# Consumed by Vagrantfile

vagrant_platform_ip: "192.168.33.90"
vagrant_worker_count: "1"


# Consumed by terraform templates

bypass_preflight_checks: "true"

github_client_id: "fake_client_id"
github_client_secret: "fake_client_secret"

librato_enabled: "yes"
librato_email: "librato@example.com"
librato_token: "librato_token"

platform_admin_password: "password"
platform_fqdn: "travis.vagrant"
rabbitmq_password: "password"
replicated_log_level: debug
